### ISSUE TITLE
Is your OCR local or do you do the processing online?

### ISSUE THREAD

**Issue by NSExceptional** [wbaumann/SmartReceiptsiOS#351]
I want to make a simple receipt tracker for myself, none of the ones on the App Store provide the level of granularity that I need, as far as OCR.

As a starting point, I'm looking for receipt scanning OCR libraries that are open source. Is yours? I couldn't seem to find it after a few minutes of digging in the source code.

**Comment by HeinousGames** [comment]
Hi @NSExceptional 

I'm sorry, but we don't provide our own OCR implementation. We utilize Taggun.io's OCR which is not open-source. You can find more information about them on their website here: https://www.taggun.io/

**Comment by NSExceptional** [comment]
Hey that's okay! If their API can do things like grab the barcode and such, that would work for me. I really just want an app I can use to store my receipts and present the barcode again if I need to, so it would have to be able to scan and replay the barcode.
